# Values for app.

nameOverride: ms-test-lib-process-data-cache
fullnameOverride: ms-test-lib-process-data-cache
runtime: Camel

replicaCount: 1

image:
  repository: image-registry.openshift-image-registry.svc:5000/xm-entradas/ms-test-lib-process-data-cache
  pullPolicy: IfNotPresent
  tag: "0.0.2"

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}
  name: ms-test-lib-process-data-cache

podAnnotations:
  sidecar.istio.io/inject: "true"
  sidecar.istio.io/rewriteAppHTTPProbe: 'true'

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080
  targetPort: http
  protocol: TCP
  name: http

routes:
  - enabled: true
    name: ms-test-lib-process-data-cache-route
    ## Opcional, si no se especifica Openshift lo genera
    #host: consulta-saldo-gateway.apps.cluster-8d6w2.8d6w2.sandbox1784.opentlc.com
    service:
      name: ms-test-lib-process-data-cache
    targetPort: http
    ## More information: https://docs.openshift.com/container-platform/4.6/networking/routes/secured-routes.html
    tls:
      enabled: false
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
      ## IMPORTANT: Do not check 'key' into git!
      key:
      caCertificate:
      certificate:
      destinationCACertificate:

ingress:
  enabled: false
  className: ""
  annotations: {}

environments:
  - name: SPRING_APPLICATION_JSON
    value: '{"server":{"undertow":{"io-threads":10, "worker-threads":20 }}}'
  - name: JAVA_OPTIONS
    value: '-Xms640m -Xmx1024m -Dfile.encoding=ISO-8859-1'

environmentsFrom:
  - configMapRef:
      name: ms-test-lib-process-data-cache-cm
  - secretRef:
      name: ms-test-lib-process-data-cache-sc

resources:
  limits:
    cpu: 400m
    memory: 1280Mi
  requests:
    cpu: 200m
    memory: 896Mi

ports:
  name: http
  port: 8080
  protocol: TCP

probe:
  enabled: true
  liveness:
    path: /actuator/health
    port: http
    failureThreshold: 3
    initialDelaySeconds: 40
    periodSeconds: 60
    successThreshold: 1
    timeoutSeconds: 120
  readiness:
    path: /actuator/health
    port: http
    failureThreshold: 3
    initialDelaySeconds: 40
    periodSeconds: 60
    successThreshold: 1
    timeoutSeconds: 120

autoscaling:
  enabled: false
  kind: Deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  #targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

configmap:
  name: ms-test-lib-process-data-cache-cm
  data:
    server.port: "8080"
    endpoints.enabled: "false"
    endpoints.health.enabled: "true"
    camel.servlet.mapping.context-path: /ms-base/*
    camel.component.http.connect-timeout: "1000"
    camel.component.http.socket-timeout: "5000"
    rest.consumer.basePath: /ms-base
    rest.consumer.apiPath: /
    rest.consumer.apiVersion: v1.0
    rest.producer.method: GET
    rest.producer.host: api.finto.fi
    rest.producer.context: /rest/v1/search
    rest.producer.protocol: https
    cache.rhdg.host: data-grid-cluster.data-grid.svc.cluster.local
    cache.rhdg.port: "11222"
    cache.rhdg.secure: "true"
    cache.rhdg.queryBuilder: FROM co.com.xm.Properties WHERE variable='ETDP'
    cache.rhdg.nameCachePropertiesVariables: VARIABLES_PROPERTIES
    cache.rhdg.nameCacheDataVariables: VARIABLES_DATA
    cache.rhdg.nameCacheLlavesMaestras: VARIABLES_LLAVES_MAESTRAS
    cache.rhdg.processorPutData: createDataVariableProcessor
    cache.rhdg.processorPutLlavesMaestras: createLlavesProcessor
    cache.rhdg.nameMapaDataVariables: data
    cache.rhdg.nameMapaProperties: properties
    cache.rhdg.nameMapaLlavesMaestras: llaves

secret:
  enabled: true
  name: ms-test-lib-process-data-cache-sc
  data:
    cache.rhdg.username: b3BlcmF0b3I=
    cache.rhdg.password: cmVkaGF0