# Values for app.

nameOverride: ms-programador-ejecutor-variables
fullnameOverride: ms-programador-ejecutor-variables
runtime: Quarkus

replicaCount: 1

image:
  repository: image-registry.openshift-image-registry.svc:5000/xm-entradas/ms-programador-ejecutor-variables
  pullPolicy: IfNotPresent
  tag: "1.0.1"

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}
  name: ms-programador-ejecutor-variables

podAnnotations:
  sidecar.istio.io/inject: "true"
  sidecar.istio.io/rewriteAppHTTPProbe: 'true'

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080
  targetPort: http
  protocol: TCP
  name: http

routes:
  - enabled: true
    name: ms-programador-ejecutor-variables-route
    ## Opcional, si no se especifica Openshift lo genera
    #host: consulta-saldo-gateway.apps.cluster-8d6w2.8d6w2.sandbox1784.opentlc.com
    service:
      name: ms-programador-ejecutor-variables
    targetPort: http
    ## More information: https://docs.openshift.com/container-platform/4.6/networking/routes/secured-routes.html
    tls:
      enabled: false
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
      ## IMPORTANT: Do not check 'key' into git!
      key:
      caCertificate:
      certificate:
      destinationCACertificate:

ingress:
  enabled: false
  className: ""
  annotations: {}

environments:
  - name: SPRING_APPLICATION_JSON
    value: '{"server":{"undertow":{"io-threads":10, "worker-threads":20 }}}'
  - name: JAVA_OPTIONS
    value: '-Xms320m -Xmx640m -Dfile.encoding=ISO-8859-1'

environmentsFrom:
  - configMapRef:
      name: ms-programador-ejecutor-variables-cm
  - secretRef:
      name: ms-programador-ejecutor-variables-sc

resources:
  limits:
    cpu: 200m
    memory: 640Mi
  requests:
    cpu: 100m
    memory: 320Mi

ports:
  name: http
  port: 8080
  protocol: TCP

probe:
  liveness:
    path: /api/v1/scheduler/health/live
    port: http
    failureThreshold: 3
    initialDelaySeconds: 5
    periodSeconds: 60
    successThreshold: 1
    timeoutSeconds: 120
  readiness:
    path: /api/v1/scheduler/health/ready
    port: http
    failureThreshold: 3
    initialDelaySeconds: 5
    periodSeconds: 60
    successThreshold: 1
    timeoutSeconds: 120

autoscaling:
  enabled: false
  kind: Deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  #targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

configmap:
  name: ms-programador-ejecutor-variables-cm
  data:
    quarkus.datasource.db-kind: postgresql
    quarkus.datasource.jdbc.url: "jdbc:postgresql://postgresql.data-grid.svc.cluster.local:5432/db"
    quarkus.hibernate-orm.database.generation: none
    quarkus.hibernate-orm.log.sql: "true"
    quarkus.hibernate-orm.sql-load-script: no-file
    quarkus.qpid-jms.url: "amqp://broker-dev-aceptor-0-svc.amq.svc.cluster.local:5672"
    scheduler.queue.name: VAR.IN.EXECUTE.QUEUE
    quarkus.smallrye-health.root-path: /api/v1/scheduler/health

secret:
  enabled: true
  name: ms-programador-ejecutor-variables-sc
  data:
    quarkus.datasource.username: dXNlcg==
    quarkus.datasource.password: cGFzcw==
    quarkus.qpid-jms.username: YWRtaW4=
    quarkus.qpid-jms.password: YWRtaW4=