{{- if .Values.configmaps }}
{{- range $configmap := .Values.configmaps }}
{{- if $configmap.enabled }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $configmap.name }}
data: 
  {{- toYaml $configmap.data | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}