{{- if .Values.deployment }}
{{- if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- if .Values.deployment.podSecurityContext -}}
      securityContext:
        {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.storages }}
      volumes:
        {{- range $storage := .Values.deployment.storages }}
        {{- if $storage.enabled }}
        - name: {{ $storage.name }}
          persistentVolumeClaim:
            claimName: {{ $storage.name }}
        {{- end }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ include "app.fullname" . }}
          {{- if .Values.deployment.securityContext -}}
          securityContext:
            {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
          {{- if .Values.deployment.environments }}
          env:
            {{- toYaml .Values.deployment.environments | nindent 12 }}
          {{- end }}
          {{- if .Values.deployment.environmentsFrom }}
          envFrom:
            {{- toYaml .Values.deployment.environmentsFrom | nindent 12 }}
          {{- end }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          {{- if .Values.deployment.storages }}
          volumeMounts:
            {{- range $storage := .Values.deployment.storages }}
            {{- if $storage.enabled }}
            - name: {{ $storage.name }}
              mountPath: {{ $storage.mountPath }}
            {{- end }}
            {{- end }}
          {{- end }}
          ports:
            - name: {{ .Values.deployment.ports.name | default "http" }}
              containerPort: {{ .Values.deployment.ports.port }}
              protocol: {{ .Values.deployment.ports.protocol | default "TCP" }}
          {{- if .Values.deployment.probe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.deployment.probe.liveness.path }}
              port: {{ .Values.deployment.probe.liveness.port | default "http" }}
            failureThreshold: {{ .Values.deployment.probe.liveness.failureThreshold }}
            initialDelaySeconds: {{ .Values.deployment.probe.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.probe.liveness.periodSeconds }}
            successThreshold: {{ .Values.deployment.probe.liveness.successThreshold }}
            timeoutSeconds: {{ .Values.deployment.probe.liveness.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.deployment.probe.readiness.path }}
              port: {{ .Values.deployment.probe.readiness.port }}
            failureThreshold: {{ .Values.deployment.probe.readiness.failureThreshold }}
            initialDelaySeconds: {{ .Values.deployment.probe.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.probe.readiness.periodSeconds }}
            successThreshold: {{ .Values.deployment.probe.readiness.successThreshold }}
            timeoutSeconds: {{ .Values.deployment.probe.readiness.timeoutSeconds }}
          {{- end  }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}