{{- if .Values.secrets }}
{{- range $secret := .Values.secrets }}
{{- if $secret.enabled }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ $secret.name }}
type: Opaque
data:
  {{- toYaml $secret.data | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}