{{- if .Values.secret.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- toYaml .Values.secret.data | nindent 2 }}
{{- end }}
